artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://zenodo.org/record/8098720/files/taterdat.zip?download=1
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion